### ISSUE TITLE
着手しているページ

### ISSUE THREAD

**Issue by 74th** [vscodejp/handson-hello-vscode#1]
- [ ] Topic 0.1 : VS Code のインストールしよう
- [x] (doing) Topic 0.2 : Repositoryを開こう
- [x] Topic 1 : VS Code の画面と、ワークスペースを理解しよう
- [x] Topic 2 : Markdown を書いてみよう
- [x] Topic 3 : 検索して、ファイルを一気に置換しよう
- [x] Topic 4 : 拡張機能をインストールして、コマンドパレットから呼び出そう
- [x] Topic 5 : 拡張機能をインストールして、Markdown をチェックさせよう
- [x] Topic 6 : Git でファイルをコミットしよう
- [x] Topic 7 : 自分好みにカスタマイズしよう
- [x] Topic 8 : スニペットで定型文を簡単に入力しよう
- [x] Topic 9 : ターミナルを活用しよう

**Comment by 74th** [comment]
レビューしてみたなど、コメントあれば、ISSUEきってお願いします。

**Comment by TakumiHANAUE** [comment]
@74th コンテンツ作り手伝います！  
Topic 7着手します。topic7作成用のブランチ切りますね :smiley:

**Comment by KeisukeSawa** [comment]
@74th 

私もコンテンツ作り手伝います。

まずは、Topic 0.2着手します。

（Collaboratorに入れていただけると嬉しいです。）

**Comment by 74th** [comment]
@TakumiHANAUE Topic7、よろしくおねがいしますmm
@KeisukeSawa 追加しました！ Invite飛んでると思います。Topic0.2よろしくお願いしますmm

**Comment by 74th** [comment]
私もこの先に作成する記事はPRにしますね。
もし、他を見る余裕があれば、1人LGTMしたらマージするようにしたいです。

**Comment by 74th** [comment]
検索作成 https://github.com/vscodejp/handson-hello-vscode/pull/2

**Comment by 74th** [comment]
次Topic1に着手

**Comment by 74th** [comment]
と思いましたが、Topic0.2をやっていただいた後に、補完する部分をTopic1で扱ったほうが良さそうなので、Topic4にします。

**Comment by TakumiHANAUE** [comment]
topic7作成し、PRしました https://github.com/vscodejp/handson-hello-vscode/pull/3

**Comment by TakumiHANAUE** [comment]
次はTopic8に着手しますね。

**Comment by 74th** [comment]
Topic4作成しました https://github.com/vscodejp/handson-hello-vscode/pull/4 。見ていただけると助かります。
次Topic5に移ります

**Comment by 74th** [comment]
Topic5 を作成しました #5 。
あと、次Topic 9 に移ります。

**Comment by TakumiHANAUE** [comment]
topic8作成し PRしました。https://github.com/vscodejp/handson-hello-vscode/pull/6

**Comment by 74th** [comment]
Topic 9 作成しました。 #9

**Comment by TakumiHANAUE** [comment]
次、Topic1着手します。

**Comment by TakumiHANAUE** [comment]
Topic1作成しました。確認お願いします。https://github.com/vscodejp/handson-hello-vscode/pull/12
